### ISSUE TITLE
TypeError: 'type' object is not subscriptable - image_downloading.py on line 105

### ISSUE THREAD

**Issue by pineapplelogic174** [andolg/satellite-imagery-downloader#1]
image_size function in image_downloading.py returns:
"TypeError: 'type' object is not subscriptable"

Appears to be in setting tile_size: int.

Debugging returns:
<class 'tuple'>[(class 'int'>, <class 'int'>)]

**Comment by pineapplelogic174** [comment]
Resolved with: https://stackoverflow.com/questions/71041586/typeerror-type-object-is-not-subscriptable

**Comment by andolg** [comment]
Thanks for the report! It seems that hints with square brackets only work in Python 3.9+, so I decided to remove it.
