### ISSUE TITLE
Scale and pixels to meters

### ISSUE THREAD

**Issue by shreejalt** [andolg/satellite-imagery-downloader#4]
Hi, 
Thanks for your contribution. I wanted to know whether there is any method to get the pixels to meters ratio in these rectangular images?

**Comment by andolg** [comment]
Hello, thanks for your interest. The images are built at some given zoom level without compression. When working with the Mercator projection, we can calculate the ground resolution (meters/pixel) at any latitude and zoom level using the following formula:

`ground resolution = earth circumference * cos(latitude) / map width`

assuming we use 256 x 256 pixel tiles:

`ground resolution = 2 * pi * 6378137 * cos(latitude) / (256 * (2 ^ zoomlevel))`

which equals to

`ground resolution = 156543.034 * cos(latitude) / (2 ^ zoomlevel)`

You can find more information about scale and resolution in Bing documentation:
https://learn.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system#ground-resolution-and-map-scale
https://learn.microsoft.com/en-us/bingmaps/articles/understanding-scale-and-resolution

**Comment by shreejalt** [comment]
Hi @andolg 
Thanks for your response.

Is this also applicable if we extract a non-square image?

**Comment by andolg** [comment]
Hi,
The shape of the image doesn't affect the ground resolution. What it really depends on is the latitude of a particular pixel.
If you are working with a large region, the `cos(latitude)` won't be the same for different parts of the image from north to south, so you might need to calculate the resolution for different places separately. However, if the region is small enough, and the latitude doesn't differ that much, you can calculate the resolution for the entire image at once with decent precision.

**Comment by andolg** [comment]
I'm sorry, but I don't understand your question. What do you mean by non-square tile resolution?
All map services that implement the Mercator projection use square tiles. The image is built out of such tiles without any distortion.
