### ISSUE TITLE
Using 512x512 pixel size of tile

### ISSUE THREAD

**Issue by rose-jinyang** [andolg/satellite-imagery-downloader#6]
Hello
How are you?
Thanks for contributing to this project.
Is it possible to download & assemble 512x512 pixel size of tile?
I tried it in your project and it failed.

**Comment by andolg** [comment]
Hi, I'm doing great. How about you?
The program should work with 512x512 tiles. Did you change the tile size in preferences.json? Also, what tiles are you using?
